apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    k8s-app: domoticz
  name: domoticz

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: domoticz
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: domoticz
      name: domoticz
    spec:
      containers:
      - env:
        - name: WWW_PORT
          value: "80"
        image: domoticz/domoticz:stable
        imagePullPolicy: IfNotPresent
        name: domoticz
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
1