apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: nodered
  name: nodered
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: nodered
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: https://nodered.org/docs/getting-started/docker
      creationTimestamp: null
      labels:
        k8s-app: nodered
      name: nodered
    spec:
      containers:
      - image: nodered/node-red
        imagePullPolicy: Always
        name: nodered
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: data
