apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: openhab
  name: openhab
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: openhab
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: https://hub.docker.com/r/openhab/openhab/#starting-with-docker-named-volumes-for-beginners
      creationTimestamp: null
      labels:
        k8s-app: openhab
      name: openhab
    spec:
      containers:
      - env:
        - name: EXTRA_JAVA_OPTS
          value: -Duser.timezone=Europe/Berlin
        - name: OPENHAB_HTTP_PORT
          value: "80"
        - name: OPENHAB_HTTPS_PORT
          value: "443"
        image: openhab/openhab
        imagePullPolicy: Always
        name: openhab
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /openhab/addons
          name: addons
        - mountPath: /openhab/conf
          name: conf
        - mountPath: /openhab/userdata
          name: userdata
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: addons
      - emptyDir: {}
        name: conf
      - emptyDir: {}
        name: userdata
